name: Kani CI
on:
  pull_request:
  push:
jobs:
  run-kani:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3

      - name: Kani Rust Verifier
        uses: model-checking/kani-github-action@v0.29
